"""sqlalchemy

Revision ID: b0bf9f0b9446
Revises: 927a773be59d
Create Date: 2021-04-18 14:57:41.288087

"""
import sqlalchemy as sa
from sqlalchemy.schema import CreateSequence, DropSequence, Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision = "b0bf9f0b9446"
down_revision = "927a773be59d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence("productsxinvoices_id_seq")))
    op.add_column(
        "productsxinvoices",
        sa.Column("id", sa.Integer(), nullable=False, server_default=sa.text("nextval('productsxinvoices_id_seq'::regclass)")),
    )
    op.create_index(op.f("productsxinvoices_id_idx"), "productsxinvoices", ["id"], unique=False)
    op.drop_constraint("templates_user_id_key", "templates", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("templates_user_id_key", "templates", ["user_id", "name"])
    op.drop_index(op.f("productsxinvoices_id_idx"), table_name="productsxinvoices")
    op.drop_column("productsxinvoices", "id")
    op.execute(DropSequence(Sequence("productsxinvoices_id_seq")))
    # ### end Alembic commands ###
